---
- name: Build Docker Image from Git Repository
  hosts: all
  become: true
  tasks:
    - name: Clone the repository
      git:
        repo: 'https://github.com/HaithamAmireh/nextjs-small'
        dest: /home/ubuntu
        version: main  # Change to your desired branch/tag

    - name: Build Docker image
      docker_image:
        path: /home/ubuntu/nextjs-small
        name: next-sema
        tag: latest
        state: present
        source: build

    - name: Remove the cloned repository
      file:
        path: /home/ubuntu/next.js
        state: absent
